#!/bin/bash
# Security Architecture Analysis Script
# Generated by android-security-architecture-upgrade skill

set -e

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "${BLUE}📊 SafeVault Security Architecture Analysis${NC}"
echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo ""

# Detect current version
echo -e "${YELLOW}🔍 Detecting current architecture version...${NC}"

LEGACY_CLASSES=(
    "KeyManager"
    "CryptoManager"
    "BackupCryptoUtil"
    "KeyDerivationManager"
)

NEW_CLASSES=(
    "SecureKeyStorageManager"
    "Argon2KeyDerivationManager"
    "CryptoSession"
)

ALGORITHMS=(
    "PBKDF2"
    "Argon2"
)

# Check for legacy classes
LEGACY_FOUND=0
for class in "${LEGACY_CLASSES[@]}"; do
    if grep -r "$class" app/src/main/java/ > /dev/null 2>&1; then
        echo -e "${RED}  ✗ Found legacy class: $class${NC}"
        LEGACY_FOUND=1
    fi
done

# Check for new classes
NEW_FOUND=0
for class in "${NEW_CLASSES[@]}"; do
    if grep -r "$class" app/src/main/java/ > /dev/null 2>&1; then
        echo -e "${GREEN}  ✓ Found new class: $class${NC}"
        NEW_FOUND=1
    fi
done

# Detect key derivation algorithm
if grep -r "PBKDF2" app/src/main/java/ > /dev/null 2>&1; then
    echo -e "${YELLOW}  ⚠ Key Derivation: PBKDF2 (legacy)${NC}"
    ALGO="PBKDF2"
elif grep -r "Argon2" app/src/main/java/ > /dev/null 2>&1; then
    echo -e "${GREEN}  ✓ Key Derivation: Argon2id (current)${NC}"
    ALGO="Argon2id"
else
    echo -e "${YELLOW}  ⚠ Key Derivation: Unknown${NC}"
    ALGO="Unknown"
fi

# Determine version
if [ "$NEW_FOUND" -eq 1 ] && [ "$ALGO" == "Argon2id" ]; then
    VERSION="v3 (Current)"
    STATUS="${GREEN}✓ Up to date${NC}"
elif [ "$LEGACY_FOUND" -eq 1 ] && [ "$ALGO" == "PBKDF2" ]; then
    VERSION="v2 (Legacy)"
    STATUS="${RED}✗ Needs upgrade${NC}"
elif [ "$LEGACY_FOUND" -eq 1 ]; then
    VERSION="v1 (Deprecated)"
    STATUS="${RED}✗ Urgent upgrade needed${NC}"
else
    VERSION="Unknown"
    STATUS="${YELLOW}⚠ Cannot determine${NC}"
fi

echo ""
echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "Current Version: ${BLUE}$VERSION${NC}"
echo -e "Status: $STATUS"
echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo ""

# Analyze affected files
echo -e "${YELLOW}📁 Analyzing affected files...${NC}"

AFFECTED_FILES=()
for class in "${LEGACY_CLASSES[@]}"; do
    while IFS= read -r file; do
        if [[ ! " ${AFFECTED_FILES[@]} " =~ " ${file} " ]]; then
            AFFECTED_FILES+=("$file")
        fi
    done < <(grep -rl "$class" app/src/main/java/ 2>/dev/null || true)
done

TOTAL_FILES=${#AFFECTED_FILES[@]}
echo -e "  Total files affected: ${YELLOW}$TOTAL_FILES${NC}"

if [ $TOTAL_FILES -gt 0 ]; then
    echo ""
    echo -e "${YELLOW}Files requiring modification:${NC}"
    for file in "${AFFECTED_FILES[@]}"; do
        echo -e "  ${RED}✏️  ${file#app/src/main/java/}${NC}"
    done
fi

echo ""
echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "${YELLOW}Recommendation:${NC}"

if [ "$VERSION" == "v3 (Current)" ]; then
    echo -e "  ${GREEN}✓ Architecture is up to date. No migration needed.${NC}"
elif [ "$VERSION" == "v2 (Legacy)" ]; then
    echo -e "  ${YELLOW}⚠ Upgrade to v3 recommended:${NC}"
    echo -e "     Use skill: android-security-architecture-upgrade"
    echo -e "     Migration: v2 → v3 (PBKDF2 → Argon2id)"
else
    echo -e "  ${RED}✗ Urgent upgrade required:${NC}"
    echo -e "     Use skill: android-security-architecture-upgrade"
    echo -e "     Migration: Current version → v3"
fi

echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
